In [1]:
import sys
sys.path.append('../src')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from data_processing import DataLoader
from feature_engineering import FeatureEngineer
from preprocessing import DataPreprocessor, PreprocessingConfig

### 1. Load Cleaned Fraud Data
Load the merged, cleaned fraud dataset from EDA.

In [2]:
loader = DataLoader("../data/processed/fraud_data_merged.csv")
fraud_data = loader.load_data()

# Show dtypes to verify
print("Data types:\n", fraud_data.dtypes)

2026-02-17 02:33:22,975 [INFO] Loading data from ../data/processed/fraud_data_merged.csv
2026-02-17 02:33:23,195 [INFO] Loaded 151112 rows and 13 columns

Data types:
 user_id             int64
signup_time        object
purchase_time      object
purchase_value      int64
device_id          object
source             object
browser            object
sex                object
age                 int64
ip_address        float64
class               int64
ip_int              int64
country            object
dtype: object

#### Ensure Correct Data Types
Convert `purchase_time` and `signup_time` to datetime for time-based feature generation.

In [3]:
fraud_data['purchase_time'] = pd.to_datetime(fraud_data['purchase_time'], errors='coerce')
fraud_data['signup_time'] = pd.to_datetime(fraud_data['signup_time'], errors='coerce')
print(fraud_data[['purchase_time', 'signup_time']].info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151112 entries, 0 to 151111
Data columns (total 2 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   purchase_time  151112 non-null  datetime64[ns]
 1   signup_time    151112 non-null  datetime64[ns]
dtypes: datetime64[ns](2)
memory usage: 2.3 MB
None

### 2. Feature Engineering - Fraud_Data
Initialize FeatureEngineer

In [4]:
fe_fraud = FeatureEngineer(fraud_data)

#### 2a. Time-based feature
Add hour of day, day of week, and time since signup (in hours).

In [5]:
fraud_data = fe_fraud.add_time_features_fraud(
    purchase_col="purchase_time",
    signup_col="signup_time"
)
fraud_data[['hour_of_day', 'day_of_week', 'time_since_signup']].head()

2026-02-17 02:33:23,301 [INFO] Added time features: hour_of_day, day_of_week, time_since_signup

   hour_of_day  day_of_week  time_since_signup
0            2            5        1251.856111
1            1            0           4.984444
2           18            3           0.000278
3           13            0         136.690278
4           18            2        1211.516944

#### 2b. Transaction frequency / velocity

In [6]:
fraud_data = fe_fraud.add_transaction_counts(group_cols=["user_id", "device_id", "country"])
fraud_data[['user_id_tx_count', 'device_id_tx_count', 'country_tx_count']].head()

2026-02-17 02:33:23,422 [INFO] Added transaction count features for columns: ['user_id', 'device_id', 'country']

   user_id_tx_count  device_id_tx_count  country_tx_count
0                 1                   1              7306
1                 1                   1             58049
2                 1                  12             58049
3                 1                   1             21966
4                 1                   1             58049

#### 2c. Scale numerical features
Standard scaling applied to `purchase_value` and `time_since_signup` for model compatibility.

In [7]:
numerical_cols = ["purchase_value", "time_since_signup"]
fraud_data = fe_fraud.scale_numerical(numerical_cols, method="standard")

fraud_data[numerical_cols].head()

2026-02-17 02:33:23,437 [INFO] Scaled columns ['purchase_value', 'time_since_signup'] using standard scaler

   purchase_value  time_since_signup
0       -0.160204          -0.136057
1       -1.142592          -1.571877
2       -1.197169          -1.577617
3        0.385567          -1.420213
4        0.112681          -0.182509

#### 2d. Encode categorical features
One-hot encode `sex`, `browser`, `source`, and `country`.

In [8]:
categorical_cols = ["sex", "browser", "source", "country"]
fraud_data = fe_fraud.encode_categorical(categorical_cols)

fraud_data.shape

2026-02-17 02:33:23,743 [INFO] Encoded categorical columns: ['sex', 'browser', 'source', 'country']

(151112, 203)

### Model Preparation (Train/Test Split & Class Balancing)
We prepare the dataset for modeling by:
- Dropping identifier columns to prevent data leakage
- Performing a stratified train-test split
- Applying SMOTE only on the training data to address class imbalance

In [9]:
config = PreprocessingConfig(
    target_col="class",
    drop_cols=['user_id', 'signup_time', 'purchase_time', 'device_id', 'ip_address']
)

In [10]:
preprocessor = DataPreprocessor(fraud_data, config)

### 3. Train-Test Split

In [11]:
X_train, X_test, y_train, y_test = preprocessor.split()

2026-02-17 02:33:24,097 [INFO] Training (before SMOTE) class distribution:
class
0    109568
1     11321
Name: count, dtype: int64
2026-02-17 02:33:24,097 [INFO] Test class distribution:
class
0    27393
1     2830
Name: count, dtype: int64

### 4. Handle Class Imbalance with SMOTE

In [12]:
X_train, y_train = preprocessor.apply_smote(X_train, y_train)

2026-02-17 02:33:25,221 [INFO] Training (after SMOTE) class distribution:
class
0    109568
1    109568
Name: count, dtype: int64

We use SMOTE instead of undersampling to avoid discarding majority class data. Since fraud detection datasets are highly imbalanced, undersampling may remove valuable legitimate transaction patterns. SMOTE generates synthetic minority samples, allowing the model to learn fraud characteristics while preserving overall dataset information.

 ### 5. Save Engineered Dataset

In [13]:
loader.df = fraud_data
loader.save_data("../data/processed/fraud_data_features.csv")

2026-02-17 02:33:32,431 [INFO] Saved DataFrame to ../data/processed/fraud_data_features.csv (151112 rows)